#ifndef VERILATOR_INTERFACE_H
#define VERILATOR_INTERFACE_H

#include "obj_dir/Vtop.h" // Generated by Verilator

class VerilatorInterface
{
public:
    VerilatorInterface() : top(new Vtop) {}

    void step()
    {
        top->eval();
    }

    void set_input(int signal, int value)
    {
        // Assume top has an input called `in_signal`
        top->in_signal = value;
    }

    int get_output(int signal)
    {
        return top->out_signal;
    }

private:
    Vtop *top;
};

#endif
